"""initial

Revision ID: 9c392a7017b3
Revises: 
Create Date: 2026-08-29 15:20:50.906709

"""
from typing import Sequence, Union
import geoalchemy2
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c392a7017b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambulance_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('base_location', sa.String(length=255), nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=False),
    sa.Column('mems_level', sa.String(length=50), nullable=True),
    sa.Column('doctor_contacts', sa.Text(), nullable=True),
    sa.Column('pilot_contacts', sa.Text(), nullable=True),
    sa.Column('call_number', sa.String(length=20), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_ambulance_units_id'), 'ambulance_units', ['id'], unique=False)
    op.create_table('dindis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('route_type', sa.Enum('ON_FOOT', 'VEHICLE', 'MIXED', name='route_type'), nullable=False),
    sa.Column('accepting_members', sa.Boolean(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('pramukh_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='dindi_status'), nullable=False),
    sa.Column('village', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('extra_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['pramukh_user_id'], ['users.id'], name='fk_dindis_pramukh_user_id', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dindis_id'), 'dindis', ['id'], unique=False)
    op.create_table('donation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dindi_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_amount', sa.Integer(), nullable=False),
    sa.Column('current_amount', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('FOOD', 'MEDICAL', 'TRANSPORT', 'GENERAL', 'OTHER', name='donation_category'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'FULFILLED', 'CANCELLED', name='donation_status'), nullable=False),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['dindi_id'], ['dindis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donation_requests_dindi_id'), 'donation_requests', ['dindi_id'], unique=False)
    op.create_index(op.f('ix_donation_requests_id'), 'donation_requests', ['id'], unique=False)
    op.create_table('facility_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('TOILET', 'NIGHT_STAY', 'WATER', 'MEDICAL', 'FOOD', 'OTHER', name='facility_category'), nullable=False),
    sa.Column('verified_by_admin', sa.Boolean(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('dindi_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hours', sa.String(length=255), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['dindi_id'], ['dindis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_facility_points_location', 'facility_points', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_facility_points_dindi_id'), 'facility_points', ['dindi_id'], unique=False)
    op.create_index(op.f('ix_facility_points_id'), 'facility_points', ['id'], unique=False)
    op.create_table('live_location_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dindi_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['dindi_id'], ['dindis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_live_location_logs_location', 'live_location_logs', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_live_location_logs_dindi_id'), 'live_location_logs', ['dindi_id'], unique=False)
    op.create_index(op.f('ix_live_location_logs_id'), 'live_location_logs', ['id'], unique=False)
    op.create_index(op.f('ix_live_location_logs_timestamp'), 'live_location_logs', ['timestamp'], unique=False)
    op.create_table('resource_needs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dindi_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('FOOD', 'WATER', 'MEDICAL', 'TRANSPORT', 'VOLUNTEERS', 'OTHER', name='resource_need_category'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'FULFILLED', name='resource_need_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['dindi_id'], ['dindis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resource_needs_location', 'resource_needs', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_resource_needs_dindi_id'), 'resource_needs', ['dindi_id'], unique=False)
    op.create_index(op.f('ix_resource_needs_id'), 'resource_needs', ['id'], unique=False)
    op.create_table('route_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dindi_id', sa.Integer(), nullable=False),
    sa.Column('stop_name', sa.String(length=255), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('scheduled_arrival', sa.DateTime(), nullable=True),
    sa.Column('scheduled_departure', sa.DateTime(), nullable=True),
    sa.Column('is_current_stop', sa.Boolean(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['dindi_id'], ['dindis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_route_stops_location', 'route_stops', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_route_stops_dindi_id'), 'route_stops', ['dindi_id'], unique=False)
    op.create_index(op.f('ix_route_stops_id'), 'route_stops', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('DINDI_PRAMUKH', 'WALKER', 'VOLUNTEER', name='user_role'), nullable=False),
    sa.Column('dindi_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dindi_id'], ['dindis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('join_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dindi_id', sa.Integer(), nullable=False),
    sa.Column('joining_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='join_request_status'), nullable=False),
    sa.Column('extra_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['dindi_id'], ['dindis.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_join_requests_dindi_id'), 'join_requests', ['dindi_id'], unique=False)
    op.create_index(op.f('ix_join_requests_id'), 'join_requests', ['id'], unique=False)
    op.create_index(op.f('ix_join_requests_user_id'), 'join_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_join_requests_user_id'), table_name='join_requests')
    op.drop_index(op.f('ix_join_requests_id'), table_name='join_requests')
    op.drop_index(op.f('ix_join_requests_dindi_id'), table_name='join_requests')
    op.drop_table('join_requests')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_route_stops_id'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_dindi_id'), table_name='route_stops')
    op.drop_index('idx_route_stops_location', table_name='route_stops', postgresql_using='gist')
    op.drop_table('route_stops')
    op.drop_index(op.f('ix_resource_needs_id'), table_name='resource_needs')
    op.drop_index(op.f('ix_resource_needs_dindi_id'), table_name='resource_needs')
    op.drop_index('idx_resource_needs_location', table_name='resource_needs', postgresql_using='gist')
    op.drop_table('resource_needs')
    op.drop_index(op.f('ix_live_location_logs_timestamp'), table_name='live_location_logs')
    op.drop_index(op.f('ix_live_location_logs_id'), table_name='live_location_logs')
    op.drop_index(op.f('ix_live_location_logs_dindi_id'), table_name='live_location_logs')
    op.drop_index('idx_live_location_logs_location', table_name='live_location_logs', postgresql_using='gist')
    op.drop_table('live_location_logs')
    op.drop_index(op.f('ix_facility_points_id'), table_name='facility_points')
    op.drop_index(op.f('ix_facility_points_dindi_id'), table_name='facility_points')
    op.drop_index('idx_facility_points_location', table_name='facility_points', postgresql_using='gist')
    op.drop_table('facility_points')
    op.drop_index(op.f('ix_donation_requests_id'), table_name='donation_requests')
    op.drop_index(op.f('ix_donation_requests_dindi_id'), table_name='donation_requests')
    op.drop_table('donation_requests')
    op.drop_index(op.f('ix_dindis_id'), table_name='dindis')
    op.drop_table('dindis')
    op.drop_index(op.f('ix_ambulance_units_id'), table_name='ambulance_units')
    op.drop_table('ambulance_units')
    # ### end Alembic commands ###
